services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=98765
    ports:
      - 5433:5432
    volumes:
      - /var/lib/posgresql/data
  mongodb:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=98765
    ports:
      - 27017:27017
    volumes:
      - /var/lib/mongodb/data